rm(list = ls())

# Problem 2: Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values 
# do not exceed four million, find the sum of the even-valued terms.

even_fibonacci <- function(n_max) {
  i <- 1
  j <- 2
  f <- c(i,j)
  while (TRUE) {
    if (i+j > n_max) break
    f <- c(f, i+j)
    i <- j
    j <- f[length(f)]
  }
  return(sum(f[f %% 2 == 0]))
}

even_fibonacci(4000000)
