rm(list = ls())

# Problem 2: Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values 
# do not exceed four million, find the sum of the even-valued terms.

# Fibonacci values until 4 million
f <- c(0)
new <- 1
while (new < 4000000) {
  f <- c(f,new)
  new <- f[length(f)-1] + f[length(f)]
}

# sum of even values
sum(f[f %% 2 == 0])